SM:
   process_name: SM
   components:
            - qq_Zh
            - gg_Zh_SM
            - gg_Zh_box
            - gg_Zh_int
            - gg_Zh_tri

2HDM:
   process_name: 2HDMtII_NLO 
   components:
            - qq_Zh
            - gg_Zh_SM
            - gg_Zh_box
            - gg_Zh_int
            - gg_Zh_tri
            - gg_Zh_A
            - gg_Zh_all

distribution_types:
               - mZh
               - Pt
               - Eta
